// import type { Metadata } from "next";
import type { PropsWithChildren } from 'react';
import NextIntlProvider from '@/core/i18n/NextIntlProvider';
import { ThemeProvider } from '@/core/theming/ThemeProvider';
import '@/core/theming/globals.css';

// export const metadata: Metadata = {
//   title: "Théo Bayenet - Front Developer",
//   description: "Generated by create next app",
// };

export async function generateStaticParams() {
  return (
    process.env.NEXT_PUBLIC_SUPPORTED_LOCALES?.split(',').map((locale) => ({
      locale,
    })) || []
  );
}

export default async function RootLayout({
  children,
  params: rawParams,
}: PropsWithChildren<{
  params: any;
}>) {
  const params = await rawParams;
  const locale = params.locale || process.env.NEXT_PUBLIC_DEFAULT_LOCALE;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <NextIntlProvider locale={params.locale}>
          <ThemeProvider>{children}</ThemeProvider>
        </NextIntlProvider>
      </body>
    </html>
  );
}
