// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import type { PropsWithChildren } from 'react';
import NextIntlProvider from '@/core/i18n/NextIntlProvider';
import { ThemeProvider } from '@/core/theming/ThemeProvider';
import '@/core/theming/globals.css';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Théo Bayenet - Front Developer",
//   description: "Generated by create next app",
// };

export async function generateStaticParams() {
  return (
    process.env.NEXT_PUBLIC_SUPPORTED_LOCALES?.split(',').map((locale) => ({
      locale,
    })) || []
  );
}

export default async function RootLayout({
  children,
  params: rawParams,
}: PropsWithChildren<{
  params: any;
}>) {
  const params = await rawParams;
  const locale = params.locale || process.env.NEXT_PUBLIC_DEFAULT_LOCALE;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlProvider locale={params.locale}>
          <ThemeProvider>{children}</ThemeProvider>
        </NextIntlProvider>
      </body>
    </html>
  );
}
